version: '3'
services:
  reverseproxy:
    build:
      context: .
    image: guilleeh/reverseproxy
  backend_user:
    build:
      context: ../../udagram-api-user
    image: guilleeh/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: guilleeh/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend
    image: guilleeh/udagram-frontend:local
